### ISSUE TITLE
🐛: Improperly marks duplicate letters green

### ISSUE THREAD

**Issue by gitKrystan** [NullVoxPopuli/ember-wordle#6]
![AFDF3B4D-1FC0-4923-95AF-C2259996FD92](https://user-images.githubusercontent.com/14152574/150857603-5f0ca501-53c6-4b4b-99dd-06ca06c2a765.jpeg)

If the same letter appears twice, both appearances will be marked green even if that’s not quite correct.

**Comment by NullVoxPopuli** [comment]
Thanks for reporting!!

which day were you playing? (in the URL)

**Comment by gitKrystan** [comment]
Should I mark this with “spoiler alert”? IDK if everyone gets the same puzzle like in the OG Wordle.

**Comment by gitKrystan** [comment]
https://ember-wordle.pages.dev/2022-01-24

**Comment by NullVoxPopuli** [comment]
> IDK if everyone gets the same puzzle like in the OG Wordle.

it was the intent, but something is goofy 
![image](https://user-images.githubusercontent.com/199018/150862181-73bcc0b4-3df6-4cc8-8021-a54113ad5470.png)

_but_, I see this:
![image](https://user-images.githubusercontent.com/199018/150862572-38095365-867d-40f9-931c-3b1a32070229.png)

I wonder if the cloudflare CDN is caching too heavily. I know earlier today, this issue was present -- but I fixed it here (supposedly): https://github.com/NullVoxPopuli/ember-wordle/commit/41ea84be3dc406222d107a38f4b08d99239cfc8b#diff-8fa8d01863b3b879a4896b68ee2d454641dedab24edd505fa7c0c29556d8b17bR109

**Comment by gitKrystan** [comment]
INTERESTING! I've spent my lunch break on this. 😂 Locally, the WOTD is "tasty" also. Maybe something something timezones? (I'm in PST)

**Comment by NullVoxPopuli** [comment]
perhaps!
or maybe the API to `new Date()` changes based on locale? :see_no_evil:

**Comment by gitKrystan** [comment]
The bug I found comes from this line:

https://github.com/NullVoxPopuli/ember-wordle/blob/f87d960638eb6678d792938c2cf1cec64a5eff77/app/components/board/state/actions.ts#L120

**Comment by gitKrystan** [comment]
Lunch break over, but I came up w/ the fix above.

Do you have any tips for making VSCode not freak out about the template imports syntax?

**Comment by NullVoxPopuli** [comment]
in your settings, set (maybe temporarily?) or maybe the repo can have its own settings? (I'd take a PR for this):
```
    "typescript.validate.enable": false
```
I think we'd want to keep that enabled for all gts/gjs files, and use glint instead (when glint supports gts/gjs).
(but I don't know how to set file-extension-specific settings)
